import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { subject, versionInfo, topIssues, selectedMetrics, contentHtml } =
      body;

    const versionSection = versionInfo
      ? `<tr>
           <td style="padding:8px;font-weight:bold;color:#6b7280;">Platform</td>
           <td style="padding:8px;">${versionInfo.platform}</td>
         </tr>
         <tr>
           <td style="padding:8px;font-weight:bold;color:#6b7280;">Product</td>
           <td style="padding:8px;">${versionInfo.product}</td>
         </tr>
         <tr>
           <td style="padding:8px;font-weight:bold;color:#6b7280;">Version</td>
           <td style="padding:8px;">${versionInfo.version}</td>
         </tr>`
      : '';

    const issuesSection = topIssues
      ? `<div style="margin-bottom:24px;">
           <h2 style="font-size:16px;color:#1f2937;border-bottom:2px solid #e5e7eb;padding-bottom:8px;">
             Top Issues
           </h2>
           <p style="color:#374151;line-height:1.6;">${topIssues}</p>
         </div>`
      : '';

    const metricsSection =
      selectedMetrics && selectedMetrics.length > 0
        ? `<div style="margin-bottom:24px;">
             <h2 style="font-size:16px;color:#1f2937;border-bottom:2px solid #e5e7eb;padding-bottom:8px;">
               Selected Metrics
             </h2>
             <ul style="color:#374151;line-height:1.8;">
               ${selectedMetrics.map((m: string) => `<li>${m}</li>`).join('')}
             </ul>
             <p style="color:#9ca3af;font-style:italic;">[Metric charts and tables would be inserted here]</p>
           </div>`
        : '';

    const customContent = contentHtml
      ? `<div style="margin-bottom:24px;">
           <h2 style="font-size:16px;color:#1f2937;border-bottom:2px solid #e5e7eb;padding-bottom:8px;">
             Additional Content
           </h2>
           <div>${contentHtml}</div>
         </div>`
      : '';

    const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8" /></head>
<body style="font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:20px;background:#f9fafb;">
  <div style="background:#ffffff;border-radius:8px;padding:32px;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
    <h1 style="font-size:20px;color:#111827;margin-bottom:24px;">
      ${subject || 'Camera Performance Report'}
    </h1>

    ${
      versionSection
        ? `<div style="margin-bottom:24px;">
             <h2 style="font-size:16px;color:#1f2937;border-bottom:2px solid #e5e7eb;padding-bottom:8px;">
               Version Information
             </h2>
             <table style="width:100%;border-collapse:collapse;">
               ${versionSection}
             </table>
           </div>`
        : ''
    }

    ${issuesSection}
    ${metricsSection}
    ${customContent}

    <div style="margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:12px;">
      Generated by Camera Performance Dashboard
    </div>
  </div>
</body>
</html>`;

    return NextResponse.json({ html });
  } catch {
    return NextResponse.json(
      { error: 'Failed to generate preview' },
      { status: 400 },
    );
  }
}
